# Generated by Django 3.2.dev20201231121857 on 2021-01-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'stock_stockinfo',
                'managed': False,
            },
        ),
    ]
