#배포용, for production
version: "3"

services:
  # db 컨테이너
  db:
    image: mysql:latest
    volumes:
      - mysql_data:C:\\DJGproject\\lib\\mysql
    environment:
      - MYSQL_DATABASE=django_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Gnlwls01!
    ports:
      - 3306:3306

  # Django 컨테이너
  web:
    build: .  
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - static_volume:C:\\DJGproject\\backend\\static
      - media_volume:C:\\DJGproject\\backend\\media
      - ./:C:\\DJGproject\\
    env_file:
      - ./.env
    depends_on:
      - db

# 컨테이너 내려도 데이터 유지되도록 함
# Keep data even if down containers
volumes:
  mysql_data:
  static_volume:
  media_volume: