version: "3.1"
services:

  django:
    command: bash
    container_name: django-con
    depends_on: 
      - mysql_db
    stdin_open: true
    tty: true
    image: ubuntu:16.04
    ports: 
      - "8000:8000"

  mysql_db:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: mysql-con
    environment: 
      MYSQL_ROOT_PASSWORD: "Gnlwls01!"
      MYSQL_DATABASE: "django_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "Gnlwls01!"
    image: mysql:8.0.21
    ports: 
      - "7001:3306"
